Jahia/jahia-page-composer

pom.xml, src/javascript/PageComposer/actions/PageComposerAction.jsx
https://jira.jahia.org/browse/BACKLOG-14639
=> BACKLOG-14639: Use props for action

package.json, pom.xml, src/javascript/PageComposer/PageComposer.jsx, src/javascript/PageComposer/PageComposer.register.js, src/javascript/index.js, src/javascript/init.js, webpack.config.js, webpack.shared.js, yarn.lock
https://jira.jahia.org/browse/QA-13327
=> QA-13327: Use webpack5, loader from jahia-ui-root

pom.xml, src/javascript/PageComposer/PageComposer.routes.jsx, src/javascript/PageComposer/actions/PageComposerAction.jsx
https://jira.jahia.org/browse/BACKLOG-15819
Added the Page composer access permission.
The following are included in this PR
I have considered the following implications of my change:
=> BACKLOG-15819: Page Composer Access permission

package.json, src/javascript/PageComposer/PageComposer.gql.jsx, src/javascript/PageComposer/PageComposer.jsx, yarn.lock
https://jira.jahia.org/browse/QA-13735
Implemented querying for home page path in case the path from the state is empty instead of using the hardcoded path.
=> QA-13735 remove hardcoded home path from page composer

src/javascript/PageComposer/ErrorPage.jsx, src/javascript/PageComposer/PageComposer.jsx, src/javascript/PageComposer/PageComposer.scss, src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-15311
=> BACKLOG-15311: Add error page

package.json, src/javascript/PageComposer/ErrorPage.jsx, src/javascript/PageComposer/ErrorPage.scss
https://jira.jahia.org/browse/BACKLOG-15311
=> BACKLOG-15311: Implement 404 page design

package.json, webpack.config.js, yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
The following are included in this PR
I have considered the following implications of my change:
=> BACKLOG-15984: upgrade libs

pom.xml, src/javascript/PageComposer/PageComposer.gql.jsx, src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/QA-13998
=> QA-13998 : use homePage graphql field to resolve homepage

src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/QA-14151
=> QA-14151: Fixed query string

src/main/resources/META-INF/urlrewrite-jahia-page-composer.xml
more detail in https://jira.jahia.org/browse/QA-14229
=> QA-14229 : preserve query string parameters

src/javascript/PageComposer/PageComposer.actions.jsx
https://jira.jahia.org/browse/BACKLOG-20115
Moved according to https://www.figma.com/file/coucb9WqWi85HZpLyKzn8O/DESIGN-1160%3A-Creation-of-menu-labels%2C-internal-links-and-external-links-%2B-sibling-page-as-Home?node-id=1895%3A10106&t=WwbPFO4EGf8whNHT-0
=> BACKLOG-20115: Moved menu entry

.github/workflows/manual-run.yml.disabled, .github/workflows/nightly.yml.disabled, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
=> TECH-1081 Update deprecated steps

pom.xml
https://jira.jahia.org/browse/TECH-1088
Remove default from jahia-depends
=> TECH-1088 Remove default from jahia-depends

tests/cypress/e2e/copyCutPaste.cy.ts
https://jira.jahia.org/browse/BACKLOG-20925
fix Copy Cut and paste tests
=> BACKLOG-20925 fix Copy Cut and paste tests

src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/QA-14739
=> QA-14739: Remove duplicate parameter

src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/QA-14774
=> QA-14774: Add full check for iframe error codes

src/javascript/PageComposer/PageComposer.routes.jsx
https://jira.jahia.org/browse/BACKLOG-20968
=> BACKLOG-20968: add info in primary nav

src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/BACKLOG-21332
=> BACKLOG-21332: Keep hash when adding redirect param

pom.xml, src/javascript/PageComposer/PageComposer.register.js, tests/provisioning-manifest-build.yml, tests/provisioning-manifest-snapshot.yml
https://jira.jahia.org/browse/BACKLOG-21097
=> BACKLOG-21097: Disable legacy page composer(actions,routes,redux) in registry

src/main/resources/javascript/locales/de.json, src/main/resources/javascript/locales/en.json, src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/PROJECT-XXX
The following are included in this PR
I have considered the following implications of my change:
=> BACKLOG-21463:Remove Legacy

tests/cypress/e2e/jahiaUserLanguage2.cy.ts
https://jira.jahia.org/browse/TECH-1365
Jahia user language 2 testsuite: A page should not be available when marked for deletion/deleted/unpublished
=> TECH-1365 Jahia user language 2 testsuite: A page should not be available when marked for deletion/deleted/unpublished

.github/workflows/nightly.yml
=> Split pagerduty reporting between jahia snapshot and jahia release

.github/workflows/nightly.yml
https://jira.jahia.org/browse/TECH-1508
=> TECH-1508 - Deactivate nightly test with Jahia release

tests/cypress/e2e/advancedPage.cy.ts, tests/cypress/page-object/pageComposer.ts, tests/cypress/page-object/pageComposer/pageComposerContextualMenu.ts
https://jira.jahia.org/browse/TECH-1356
fix test
=> TECH-1356 fix test

src/main/resources/META-INF/urlrewrite-jahia-page-composer.xml
https://jira.jahia.org/browse/QA-14229
=> QA-14229 TECH-1550 : update rule, disable global setting

pom.xml
https://jira.jahia.org/browse/BACKLOG-22117
As discussed in slack (BACKLOG-22116 was up-to-date but will not be used for the release)
=> BACKLOG-22117: Update parent version

.github/workflows/manual-run.yml, .github/workflows/nightly-rl.yml, .github/workflows/nightly-sn.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/on-rollback.yml, .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
=> TECH-1639 Upgrade actions

.github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-23179
=> BACKLOG-23179: Add missing parameter for the Slack notif

src/javascript/PageComposer/PageComposer.jsx
https://jira.jahia.org/browse/QA-15289
Prevent a Javascript error to occur If the home page is not available to the user (and therefore the GraphQL query would return null for the homePage field)
=> QA-15289: Prevent JS error if home page not available

.github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/on-release.yml, .github/workflows/schedule-sonar.yml, pom.xml
Because of the changes here https://github.com/Jahia/jahia-page-composer/pull/156 is compatible only with jcontent 3.2+, we are making the module compatible only with jahia 8.2 +
=> chore: Bump jahia parent to 8.2

.github/workflows/manual-run.yml, .github/workflows/nightly-rl.yml, .github/workflows/nightly-sn.yml, .github/workflows/on-code-change.yml, .github/workflows/on-merge.yml, .github/workflows/schedule-sonar.yml, tests/.env.example
Migrate to Github packages
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
=> chore: migrate to gh packages
